import { useState } from 'react'
import { simulateShot, type Shot } from '../physics/projectile'
import { addPump, activateTrajectoryVision, initialGameSession, startSkillSign } from '../learning/gameSession'
import { Button } from './components/Button'
import { EnergyBar, SkillSlot } from './components/GameHud'
import { PaperCard } from './components/PaperCard'

type Step = 'brief'|'prediction'|'tutorial'|'play'|'charge'|'sign'|'retry'|'compare'|'concept'|'summary'
export function ProjectileMission({ onExit }: { onExit: () => void }) {
  const [step,setStep]=useState<Step>('brief'); const [session,setSession]=useState(initialGameSession); const [prediction,setPrediction]=useState(''); const [angle,setAngle]=useState(45); const [speed,setSpeed]=useState(25); const [shots,setShots]=useState<Shot[]>([]); const [concept,setConcept]=useState('')
  const shot=()=>{setShots(s=>[...s,simulateShot(angle,speed)]);setStep(shots.length?'compare':'charge')}; const next=(s:Step)=>()=>setStep(s)
  const body = step==='brief'?<><h1>Basic Shot</h1><p>ยิงข้ามกำแพงให้ถึงเป้าหมาย</p><Button href="#" onClick={(e)=>{e.preventDefault();next('prediction')()}}>เริ่ม</Button></>:step==='prediction'?<><h1>ทำนายผล</h1>{['มุมกลางน่าจะไกล','แรงมากอย่างเดียวพอ','มุมสูงที่สุดดีที่สุด'].map(x=><label key={x}><input type="radio" name="p" onChange={()=>setPrediction(x)}/>{x}</label>)}<Button href="#" onClick={(e)=>{e.preventDefault();next('tutorial')()}}>ต่อไป</Button></>:step==='tutorial'?<><h1>Gesture Tutorial</h1><p>Fallback: ปรับมุมและความเร็วด้วย slider แล้วกดยิง</p><Button href="#" onClick={(e)=>{e.preventDefault();next('play')()}}>เข้า Lab</Button></>:step==='play'||step==='retry'?<><h1>{step==='retry'?'Retry Shot':'Basic Shot'}</h1><label>มุม {angle}° <input type="range" min="20" max="70" value={angle} onChange={e=>setAngle(+e.target.value)}/></label><label>ความเร็วต้น {speed}<input type="range" min="15" max="35" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><div className="mock-field">◉ ─── ▯ ─── ◎</div><Button href="#" onClick={e=>{e.preventDefault();shot()}}>ยิง (Enter)</Button></>:step==='charge'?<><h1>67 Power Charge</h1><EnergyBar energy={session.energy}/><button onClick={()=>setSession(s=>addPump(s,25))}>Space / Pump 67</button>{session.energy===100&&<Button href="#" onClick={e=>{e.preventDefault();next('sign')()}}>เริ่ม Skill Sign</Button>}</>:step==='sign'?<><h1>Skill Sign</h1><SkillSlot state={session.skill}/><button onClick={()=>setSession(s=>s.skill==='sign-step-1'?activateTrajectoryVision(s):startSkillSign(s))}>{session.skill==='sign-step-1'?'ขั้น 2: กางมือ / Enter':'ขั้น 1: ประกบมือ / Enter'}</button>{session.skill==='active'&&<><p>Trajectory Vision เปิดแล้ว: ⌒ จุดสูงสุด</p><Button href="#" onClick={e=>{e.preventDefault();next('retry')()}}>ยิงอีกครั้ง</Button></>}</>:step==='compare'?<><h1>Compare Attempts</h1>{shots.map((s,i)=><p key={i}>ครั้ง {i+1}: {s.angle}° · v{s.speed} · ระยะ {s.range} · {s.hit?'โดนเป้า':'ยังไม่โดน'}</p>)}<Button href="#" onClick={e=>{e.preventDefault();next('concept')()}}>ตรวจความเข้าใจ</Button></>:step==='concept'?<><h1>Concept Check</h1><p>การเพิ่มความเร็วต้นส่งผลต่อระยะทางอย่างไร?</p><input value={concept} onChange={e=>setConcept(e.target.value)}/><Button href="#" onClick={e=>{e.preventDefault();next('summary')()}}>สรุป</Button></>:<><h1>Learning Summary</h1><p>ทำนาย: {prediction||'-'}</p><p>ทดลอง {shots.length} ครั้ง · {shots.map(s=>s.range).join(', ')} เมตร</p><p>สิ่งที่เข้าใจ: {concept||'-'}</p><Button href="#" onClick={e=>{e.preventDefault();onExit()}}>กลับแผนที่</Button></>
  return <section className="mission-flow"><PaperCard>{body}</PaperCard></section>
}
