import { useState } from 'react'
import { initialGameSession, addPump, activateTrajectoryVision, startSkillSign } from '../learning/gameSession'
import { aimFromDrag } from '../missions/fallbackInput'
import { initialMissionState, type MissionStep } from '../missions/missionState'
import { simulateShot } from '../physics/projectile'
import { Button } from './components/Button'
import { EnergyBar, SkillSlot } from './components/GameHud'
import { PaperCard } from './components/PaperCard'

export function ProjectileMission({ onExit }: { onExit: () => void }) {
 const [mission,setMission]=useState(initialMissionState); const [game,setGame]=useState(initialGameSession); const [aim,setAim]=useState({angle:45,speed:25}); const [drag,setDrag]=useState<{x:number;y:number}|null>(null)
 const go=(step:MissionStep)=>()=>setMission(s=>({...s,step})); const launch=()=>{const shot=simulateShot(aim.angle,aim.speed);setMission(s=>({...s,attempts:[...s.attempts,shot],step:s.attempts.length?'compare':'charge'}))}
 const content=mission.step==='brief'?<><h1>ภารกิจ Basic Shot</h1><p>ยิงข้ามกำแพงให้โดนเป้าหมาย</p><Button href="#" onClick={e=>{e.preventDefault();go('prediction')()}}>เริ่มภารกิจ</Button></>:mission.step==='prediction'?<><h1>ทำนายผล</h1><label><input type="radio" name="p" onChange={()=>setMission(s=>({...s,prediction:'มุมกลางน่าจะข้ามกำแพงได้ดี'}))}/>มุมกลางน่าจะข้ามกำแพงได้ดี</label><Button href="#" onClick={e=>{e.preventDefault();go('tutorial')()}}>ต่อไป</Button></>:mission.step==='tutorial'?<><h1>Gesture Tutorial</h1><p>ลากเมาส์จากลูกบอลเพื่อเล็ง แล้วปล่อยเพื่อยิง</p><p>ปุ่ม Space ใช้จำลอง 67 Pump ได้</p><Button href="#" onClick={e=>{e.preventDefault();go('shot1')()}}>เข้า Lab</Button></>:mission.step==='shot1'||mission.step==='shot2'?<><h1>{mission.step==='shot1'?'ยิงครั้งแรก':'ยิงอีกครั้งด้วย Trajectory Vision'}</h1><div className="mock-field" onPointerDown={e=>setDrag({x:e.clientX,y:e.clientY})} onPointerUp={e=>{if(drag){setAim(aimFromDrag(drag,{x:e.clientX,y:e.clientY}));setDrag(null)}}}>◉ ─── ▯ ─── ◎<small>มุม {aim.angle}° · ความเร็ว {aim.speed}</small></div><Button href="#" onClick={e=>{e.preventDefault();launch()}}>ปล่อยยิง</Button></>:mission.step==='charge'?<><h1>67 Power Charge</h1><EnergyBar energy={game.energy}/><button onClick={()=>setGame(s=>addPump(s,25))}>Space / Pump 67</button>{game.energy===100&&<Button href="#" onClick={e=>{e.preventDefault();go('sign')()}}>ใช้ Skill Sign</Button>}</>:mission.step==='sign'?<><h1>Skill Sign</h1><SkillSlot state={game.skill}/><button onClick={()=>setGame(s=>s.skill==='sign-step-1'?activateTrajectoryVision(s):startSkillSign(s))}>{game.skill==='sign-step-1'?'ขั้น 2: กางมือ':'ขั้น 1: ประกบมือ'}</button>{game.skill==='active'&&<Button href="#" onClick={e=>{e.preventDefault();go('shot2')()}}>Trajectory Vision พร้อม</Button>}</>:mission.step==='compare'?<><h1>เปรียบเทียบการทดลอง</h1>{mission.attempts.map((a,i)=><p key={i}>ครั้ง {i+1}: มุม {a.angle}° · ความเร็ว {a.speed} · ระยะ {a.range} · {a.hit?'โดนเป้า':'ยังไม่โดน'}</p>)}<Button href="#" onClick={e=>{e.preventDefault();go('concept')()}}>ตรวจความเข้าใจ</Button></>:mission.step==='concept'?<><h1>Concept Check</h1><p>มุมและความเร็วต้นส่งผลต่อวิถีอย่างไร?</p><input onChange={e=>setMission(s=>({...s,concept:e.target.value}))}/><Button href="#" onClick={e=>{e.preventDefault();go('summary')()}}>สรุป</Button></>:<><h1>สรุปการเรียนรู้</h1><p>คำทำนาย: {mission.prediction||'ยังไม่ได้ตอบ'}</p><p>จำนวนครั้งที่ทดลอง: {mission.attempts.length}</p><p>สิ่งที่เข้าใจ: {mission.concept||'ข้อความชั่วคราว'}</p><Button href="#" onClick={e=>{e.preventDefault();onExit()}}>กลับแผนที่โลก</Button></>
 return <section className="mission-flow"><PaperCard>{content}</PaperCard></section>
}
