export const th = {
  journey: 'เริ่มการเดินทาง',
  mapTitle: 'เลือกเกาะที่อยากออกสำรวจ',
  projectile: 'การเคลื่อนที่แบบโพรเจกไทล์',
  momentum: 'แรงดลและโมเมนตัม',
  balance: 'สมดุลและแรงบิด',
  friction: 'แรงเสียดทาน',
  energyTopic: 'พลังงาน',
  islandProjectile: 'เกาะวิถีโค้ง',
  islandMomentum: 'เกาะแรงกระแทก',
  islandFriction: 'เกาะพื้นลื่น',
  islandEnergy: 'เกาะพลังงาน',
  islandMystery: 'เกาะลับ',
  islandPower67: 'เกาะพลัง 67',
  locked: 'เกาะนี้ยังล็อกอยู่',
  comingSoon: 'เกาะนี้กำลังเตรียมเปิดให้สำรวจ',
  understood: 'เข้าใจแล้ว',
  landingSceneAlt: 'ฉากห้องทดลองและสมุดฟิสิกส์',
  logoAlt: 'โลโก้ Meme Physics Lab 67',
  mascotAlt: 'มาสคอตนก 67 ถือ Tung Tung',
  hubTitle: 'ยิงข้ามกำแพงให้โดนเป้าหมาย',
  hubBody: 'ปรับมุมปล่อยและความเร็วต้น แล้วสังเกตวิถีการเคลื่อนที่',
  startMission: 'เริ่มภารกิจ',
  energy: 'พลัง 67',
  skill: 'Trajectory Vision',
  fallback: 'ใช้เมาส์หรือแป้นพิมพ์เป็นทางเลือกได้',
  temporary: 'ข้อความชั่วคราว',
  mapBack: 'กลับแผนที่',
  ready: 'พร้อมใช้',
  charging: 'ทำท่า 67 เพื่อเติมพลัง',
  energyFull: 'พลังเต็มแล้ว',
  visionActive: 'กำลังแสดงวิถี',
  fillEnergy: 'เติมพลัง 67 ให้เต็ม',
  gestureLab: 'ห้องทดลองท่าทาง',
  gestureSkill: 'ประกบมือ → กางมือ',
  gesturePump: 'ท่า 67 เพื่อเติมพลัง',
  pumpButton: 'กด Space / Pump 67',
  skillButton: 'กด Enter / Skill Sign',
  privacyFallback: 'Mouse/Keyboard fallback พร้อมใช้งาน · ไม่มีการบันทึกภาพกล้อง',
  visionPreview: 'ตัวอย่างวิถีและจุดสูงสุดโดยประมาณ',
  mission: {
    briefTitle: 'ภารกิจ Basic Shot', goal: 'ยิงข้ามกำแพงให้โดนเป้าหมาย', learningGoal: 'สังเกตผลของมุมและความเร็วต้น',
    gestureGrab: 'กำมือ', gestureAim: 'ง้าง', gestureRelease: 'ปล่อย', predictionAction: 'ไปทำนายผล',
    predictionQuestion: 'มุมไหนน่าจะข้ามกำแพงได้ดี?', predictionLow: 'มุมต่ำ', predictionMedium: 'มุมกลาง', predictionHigh: 'มุมสูง', confirm: 'ยืนยันคำทำนาย',
    tutorialTitle: 'ฝึกท่าก่อนทดลอง', tutorialBody: 'กำมือ → ง้าง → ปล่อย', startLab: 'เริ่มทดลอง', firstShot: 'ยิงครั้งแรก', retryShot: 'ยิงอีกครั้งด้วย Trajectory Vision',
    angle: 'มุม', speed: 'ความเร็วต้น', launcher: 'จุดยิง', wall: 'กำแพง', target: 'เป้าหมาย', dragGuide: 'ลากเมาส์จากจุดยิงเพื่อเล็งและปรับแรง', releaseFallback: 'ปล่อยยิง (Fallback)',
    powerTitle: 'ปั๊มพลัง 67', powerInstruction: 'สลับมือรัว ๆ เพื่อปั๊มพลัง 67', useSkill: 'ใช้ Skill Sign', signTitle: 'ทำ Skill Sign', signStepOne: '1/2 ประกบมือ', signStepTwo: '2/2 กางมือออก', nextSignStep: 'Enter / ขั้นถัดไป', visionReady: 'Trajectory Vision เปิดแล้ว',
    compareTitle: 'เปรียบเทียบการทดลอง', attempt: 'ครั้งที่', range: 'ระยะทาง', hit: 'โดนเป้าหมาย', miss: 'ยังไม่โดนเป้าหมาย', compareInsight: 'ลองปรับมุมและความเร็วต้นทีละอย่าง เพื่อสังเกตความแตกต่างของวิถี', continueAction: 'ต่อไป',
    conceptTitle: 'ตรวจความเข้าใจ', conceptQuestion: 'การเปลี่ยนมุมหรือความเร็วต้น ส่งผลต่อวิถีอย่างไร?', summaryAction: 'ดูสรุป', summaryTitle: 'สรุปการเรียนรู้', predictionLabel: 'คำทำนายก่อนเล่น', understandingLabel: 'สิ่งที่เข้าใจ', playAgain: 'เล่นอีกครั้ง', backToMap: 'กลับ World Map', noAnswer: 'ยังไม่ได้ตอบ', trajectoryAhead: 'วิถีล่วงหน้า', approximatePeak: 'จุดสูงสุดโดยประมาณ',
  },
  landingMap: {
    headline: 'ฟิสิกส์ไม่ใช่แค่จำสูตร แต่ต้องลองยิงจริง',
    support: 'เลือกท่าทางหรือเมาส์ แล้วออกสำรวจโลกฟิสิกส์สุดปั่นไปพร้อมกัน',
    quickDemo: 'โหมดทดลองด่วน',
    cameraControl: 'ใช้กล้อง', cameraControlHint: 'ขยับมือเพื่อเล็ง',
    handControl: 'เล่นด้วยมือ', handControlHint: 'กำมือ ง้าง แล้วปล่อย',
    mouseControl: 'เล่นด้วยเมาส์', mouseControlHint: 'พร้อมเป็น fallback',
    playerName: 'DEK67', menuMissions: 'ภารกิจ', menuStats: 'สถิติของฉัน', menuCollection: 'คอลเลกชัน', menuSettings: 'ตั้งค่า', progressUnit: 'ดาว',
  },
  g3: {
    landingHeadline: 'ออกเดินทางในโลกของมีม ที่ทุกท่าทางซ่อนฟิสิกส์ไว้!', landingHeadlineLines: ['ออกเดินทางในโลกของมีม', 'ที่ทุกท่าทางซ่อนฟิสิกส์ไว้!'],
    landingSupport: 'ยิงจริง สังเกตจริง แล้วค้นพบฟิสิกส์ด้วยตัวเอง',
    quickDemo: 'โหมดทดลองด่วน',
    cameraReady: 'พร้อมเชื่อมต่อกล้องในขั้นถัดไป',
    inputCamera: 'ใช้กล้อง', inputGesture: 'เล่นด้วยมือ', inputMouse: 'เล่นด้วยเมาส์ (สำรอง)',
    inputCameraHint: 'ขยับมือเพื่อเล็ง', inputGestureHint: 'กำมือ ง้าง แล้วปล่อย', inputMouseHint: 'พร้อมเป็น fallback',
    unlockCondition: 'เงื่อนไขปลดล็อก', close: 'ปิด', missionPanel: 'ภารกิจของฉัน', statisticsPanel: 'สถิติของฉัน', collectionPanel: 'คอลเลกชัน', settingsPanel: 'ตั้งค่า',
    sound: 'เสียง', animations: 'แอนิเมชัน', profileGreeting: 'นักผจญภัย DEK67', comingSoonTitle: 'กำลังจะมาเร็ว ๆ นี้',
  },
} as const
