export const th = {
  journey: 'Start exploring',
  mapTitle: 'Choose an island to explore',
  projectile: 'Projectile motion',
  momentum: 'Impulse and momentum',
  balance: 'Equilibrium and torque',
  friction: 'Friction',
  energyTopic: 'Energy',
  islandProjectile: 'Projectile Island',
  islandMomentum: 'Momentum Island',
  islandFriction: 'Friction Island',
  islandEnergy: 'Energy Island',
  islandMystery: 'Mystery Island',
  islandPower67: 'Gravity Island',
  locked: 'This island is locked',
  comingSoon: 'This island is coming soon',
  understood: 'Got it',
  landingSceneAlt: 'Physics lab and notebook scene',
  logoAlt: 'Physics Meme Lab logo',
  mascotAlt: 'Physics Meme Lab mascot with a wooden companion',
  hubTitle: 'Launch over the wall and hit the target',
  hubBody: 'Adjust launch angle and initial speed, then observe the trajectory.',
  startMission: 'Start mission',
  energy: '67 Energy',
  skill: 'Trajectory Vision',
  fallback: 'Mouse and keyboard controls are also available',
  temporary: 'Placeholder',
  mapBack: 'Back to map',
  ready: 'Ready',
  charging: 'Use the 67 gesture to charge',
  energyFull: 'Energy full',
  visionActive: 'Showing trajectory',
  fillEnergy: 'Fill your 67 energy',
  gestureLab: 'Gesture lab',
  gestureSkill: 'Bring hands together → Spread apart',
  gesturePump: '67 gesture to charge',
  pumpButton: 'Press Space / Pump 67',
  skillButton: 'Press Enter / Skill Sign',
  privacyFallback: 'Mouse/keyboard controls available · Camera footage is not recorded',
  visionPreview: 'Preview of the trajectory and approximate peak',
  mission: {
    briefTitle: 'Basic Shot mission', goal: 'Launch over the wall and hit the target', learningGoal: 'Observe the effects of angle and initial speed',
    gestureGrab: 'Make a fist', gestureAim: 'Pull back', gestureRelease: 'Release', predictionAction: 'Make a prediction',
    predictionQuestion: 'Which angle is most likely to clear the wall?', predictionLow: 'Low angle', predictionMedium: 'Medium angle', predictionHigh: 'High angle', confirm: 'Confirm prediction',
    tutorialTitle: 'Practice before experimenting', tutorialBody: 'Make a fist → Pull back → Release', startLab: 'Start lab', firstShot: 'First launch', retryShot: 'Launch again with Trajectory Vision',
    angle: 'Angle', speed: 'Initial speed', launcher: 'Launcher', wall: 'Wall', target: 'Target', dragGuide: 'Drag from the launcher to aim and adjust power', releaseFallback: 'Launch (button control)',
    powerTitle: 'Pump 67 energy', powerInstruction: 'Alternate your hands quickly to charge 67 energy', useSkill: 'Use Skill Sign', signTitle: 'Perform Skill Sign', signStepOne: '1/2 Bring hands together', signStepTwo: '2/2 Spread hands apart', nextSignStep: 'Enter / Next step', visionReady: 'Trajectory Vision activated',
    compareTitle: 'Compare attempts', attempt: 'Attempt', range: 'Range', hit: 'Target hit', miss: 'Target missed', compareInsight: 'Change one variable at a time: compare how angle and initial speed affect the trajectory.', continueAction: 'Continue',
    conceptTitle: 'Check your understanding', conceptQuestion: 'How do launch angle and initial speed change the trajectory?', summaryAction: 'View summary', summaryTitle: 'Learning summary', predictionLabel: 'Your prediction', understandingLabel: 'What I learned', playAgain: 'Play again', backToMap: 'Back to World Map', noAnswer: 'Not answered', trajectoryAhead: 'Trajectory preview', approximatePeak: 'Approximate peak',
  },
  landingMap: {
    headline: 'Physics takes more than formulas. Try a launch!',
    support: 'Choose hand gestures or mouse controls and explore a playful physics world.',
    quickDemo: 'Quick demo',
    cameraControl: 'Camera controls', cameraControlHint: 'Move your hand to aim',
    handControl: 'Hand gestures', handControlHint: 'Grab, aim, release',
    mouseControl: 'Mouse controls', mouseControlHint: 'Alternative controls available',
    playerName: 'DEK67', menuMissions: 'Missions', menuStats: 'My statistics', menuCollection: 'Collection', menuSettings: 'Settings', progressUnit: 'stars',
  },
  g3: {
    landingHeadline: 'Explore a world of memes. Discover physics in every gesture!', landingHeadlineLines: ['Play with physics', 'Learn by doing'],
    landingSupport: 'Launch. Observe. Discover.',
    quickDemo: 'Quick demo',
    cameraReady: 'Camera connection is available in the next step',
    inputCamera: 'Camera', inputGesture: 'Gestures', inputMouse: 'Mouse & keys',
    inputCameraHint: 'Move your hand to aim', inputGestureHint: 'Grab, aim, release', inputMouseHint: 'Alternative controls available',
    unlockCondition: 'How to unlock', close: 'Close', missionPanel: 'My missions', statisticsPanel: 'My statistics', collectionPanel: 'Collection', settingsPanel: 'Settings',
    sound: 'Sound', animations: 'Animations', profileGreeting: 'Explorer DEK67', comingSoonTitle: 'Coming soon',
  },
} as const
